version: 0.2

env:
  variables:
    EXCLUDE_DIRS: '^\.|scripts|modules|bin'

phases:
  install:
    runtime-versions:
      golang: 1.12
    commands:
      - wget https://github.com/mercari/tfnotify/releases/download/v0.7.0/tfnotify_linux_amd64.tar.gz
      - tar xzf tfnotify_linux_amd64.tar.gz
      - mv tfnotify /bin/tfnotify
  build:
    commands:
      - |
        if echo $CODEBUILD_SOURCE_VERSION | grep -q 'pr/'; then
          echo "PLAN MODE"
          /bin/sh scripts/plan.sh
        else
          echo "APPLY MODE"
          /bin/sh scripts/apply.sh
        fi